### PR TITLE
Switch to Pydantic v2

### PR DESCRIPTION
**Pull request by jerivas**
This PR allows the library to work with Pydantic v2 and FastAPI >= 0.100 without warnings

### CODE REVIEW

**Comment by morindo** [comment]
Can we merge this PR please?

**Comment by morindo** [comment]
Hi @jerivas, and thanks for adding support for Pydantic 2. I'm been able to pip install your PR in my FastAPI project but I'm getting this error when starting the app.

```PowerShell
pip install git+https://github.com/oddbird/fastapi-vite.git
```

```PowerShell
uvicorn main:app --reload
```

```Python
  File "C:\myfastapi\routers\dashboard.py", line 4, in <module>
    import fastapi_vite
  File "C:\myfastapi\.venv\Lib\site-packages\fastapi_vite\__init__.py", line 2, in <module>
    from fastapi_vite.config import settings
  File "C:\myfastapi\.venv\Lib\site-packages\fastapi_vite\config.py", line 5, in <module>
    from pydantic import BaseSettings, validator
  File "C:\myfastapi\.venv\Lib\site-packages\pydantic\__init__.py", line 374, in __getattr__
    return _getattr_migration(attr_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\myfastapi\.venv\Lib\site-packages\pydantic\_migration.py", line 296, in wrapper
    raise PydanticImportError(
pydantic.errors.PydanticImportError: `BaseSettings` has been moved to the `pydantic-settings` package. See https://docs.pydantic.dev/2.6/migration/#basesettings-has-moved-to-pydantic-settings for more details.
```
This is my requirements.txt file.

```Python
annotated-types==0.6.0
anyio==4.2.0
certifi==2024.2.2
click==8.1.7
colorama==0.4.6
dnspython==2.5.0
email-validator==2.1.0.post1
fastapi==0.109.2
fastapi_vite @ git+https://github.com/oddbird/fastapi-vite.git@4c928ddda769feaece178209449ef1c55b72c9e5
h11==0.14.0
httpcore==1.0.3
httptools==0.6.1
httpx==0.26.0
idna==3.6
itsdangerous==2.1.2
Jinja2==3.1.3
MarkupSafe==2.1.5
orjson==3.9.14
pydantic==2.6.1
pydantic-extra-types==2.5.0
pydantic-settings==2.1.0
pydantic_core==2.16.2
python-dotenv==1.0.1
python-multipart==0.0.9
PyYAML==6.0.1
sniffio==1.3.0
starlette==0.36.3
typer==0.9.0
typing_extensions==4.9.0
ujson==5.9.0
uvicorn==0.27.1
watchfiles==0.21.0
websockets==12.0
```

Do you have any idea how to fix this?

Thank you,

**Comment by morindo** [comment]
My bad, I was doing the wrong pip install. The correct pip install is:

```PowerShell
pip install git+https://github.com/oddbird/fastapi-vite.git@pydantic-v2
```

Now I'm getting:

```Python
    from routers import dashboard
  File "C:\myfastapi\routers\dashboard.py", line 4, in <module>
    import fastapi_vite
  File "C:\myfastapi\.venv\Lib\site-packages\fastapi_vite\__init__.py", line 2, in <module>
    from fastapi_vite.config import settings
  File "C:\myfastapi\.venv\Lib\site-packages\fastapi_vite\config.py", line 61, in <module>
    settings = ViteSettings()
               ^^^^^^^^^^^^^^
  File "C:\myfastapi\.venv\Lib\site-packages\pydantic_settings\main.py", line 71, in __init__
    super().__init__(
  File "C:\myfastapi\.venv\Lib\site-packages\pydantic\main.py", line 171, in __init__
    self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for ViteSettings
manifest_path
  Field required [type=missing, input_value={}, input_type=dict]
    For further information visit https://errors.pydantic.dev/2.6/v/missing
```

**Comment by jerivas** [comment]
I think that's telling you that VITE_MANIFEST_PATH is not defined in your env vars

**Comment by cofin** [comment]
Thank you all for continuing to work on this, and sorry it's been dormant for quite some time.

I'll try to spend some time in the coming days to get this updated and in-line with current `litestar-vite` plugin.

Please drop into the Litestar discord and send me a message if there's something that you guys would like to discuss on this repository.

Thanks again!

**Comment by jerivas** [comment]
@cofin any plans to cut a new release on PyPI to get this fix published?

**Comment by cofin** [comment]
> @cofin any plans to cut a new release on PyPI to get this fix published?

Yeah, I'll try to get one published this week.

**Pull request merged**
